Repository jamjam-book/be15-jamjam-bookjeok-combine, pull requests merged in 2025-04, with the labels that each got.

#4 [DOCS] readme 이미지 변경 및 프로젝트 회고 수정 완료
  .idea/.gitignore
  .idea/bookjeok.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  assets/Book적Book적_논리 ERD.png
  assets/restApi/1.png
  assets/restApi/2.png
  assets/restApi/3.png
  assets/restApi/4.png
  assets/restApi/5.png
  assets/restApi/6.png
  assets/restApi/7.png
  assets/test/구매/01_결제 승인 요청.png
  assets/test/구매/02_임시 주문 정보 생성.png
  assets/test/구매/03_장바구니 도서 삭제.png
  assets/test/구매/03_장바구니_장바구니 도서 삭제.png
  assets/test/구매/04_장바구니 도서 수량 변경.png
  assets/test/구매/04_장바구니_장바구니 도서 수량 변경.png
  assets/test/구매/05_장바구니 도서 등록.png
  assets/test/구매/05_장바구니_장바구니 도서 등록.png
  assets/test/구매/06_장바구니 목록 조회.png
  assets/test/구매/06_장바구니_장바구니 목록 조회.png
  assets/test/구매/07_임시 주문 정보 삭제.png
Labels: 📝 문서

#3 [CHORE] combine 프로젝트에 이슈-공통 템플릿 적용
  .github/ISSUE_TEMPLATE/이슈-공통-템플릿.md
Labels: 🗃️ 템플릿

#5 [DOCS] 팀원 회고 내용 수정
  README.md
Labels: 📝 문서

#6 [REFACTOR] JWT 설정을 환경 변수 기반으로 변경
  be15-2nd-jamjam-bookjeok/src/test/resources/application-test.yml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/application.yml
Labels: ♻️ 리팩토링, ⚙ 설정

#7 [REFACTOR] swagger에서 title 명 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/config/SwaggerConfig.java
Labels: ♻️ 리팩토링

#9 [FEATURE] 주문 내역을 조회하는 기능 구현
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/controller/OrderController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/OrderResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/PageOrderResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/repository/OrderRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/service/OrderCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/service/OrderCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/application.yml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/order/command/controller/OrderControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/order/command/service/OrderCommandServiceImplTest.java
Labels: 🤖 기능

#10 [REFACTOR] JWT 설정을 환경 변수 기반으로 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/resources/application-test.yml
Labels: ♻️ 리팩토링, ⚙ 설정

#16 [FEATURE] 회원 ID 기반 장바구니 조회 시 memberUid 대신 memberId로 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/controller/CartQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/controller/PaymentCommandController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/TossPaymentApproveRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/request/PaymentConfirmRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/infrastructure/service/TossPaymentCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/infrastructure/service/TossPaymentCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/static/success.html
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/query/controller/CartQueryControllerTest.java
Labels: 🤖 기능

#18 [REFACTOR] memberDTO에 @Builder 어노테이션 추가 및 AdminService 테스트 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/dto/MemberDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/service/AdminServiceTest.java
Labels: ♻️ 리팩토링

#20 [FEATURE] 주문 상세 내역을 조회하는 기능 구현
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/controller/OrderDetailQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/dto/response/OrderDetailResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/mapper/OrderDetailMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/service/OrderDetailQueryService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/service/OrderDetailQueryServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/orderdetail/OrderDetailMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/orderdetail/query/controller/OrderDetailQueryControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/orderdetail/query/service/OrderDetailQueryServiceImplTest.java
Labels: 🤖 기능

#21 [TEST] MemberDTO 생성 시 생성자 대신 빌더 패턴 적용
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/order/command/controller/OrderControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/orderdetail/query/controller/OrderDetailQueryControllerTest.java
Labels: ♻️ 리팩토링, ✔️ 테스트

#23 [REFACTOR] 도서 등록 / 수정 비즈니스 로직 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/controller/BookApiController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/controller/BookCommandAdminController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/service/BookApiService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/service/BookApiServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/service/BookCommandAdminService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/service/BookCommandAdminServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/test/java/com/jamjam/bookjeok/domains/book/command/controller/BookApiControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/test/java/com/jamjam/bookjeok/domains/book/command/controller/BookCommandAdminControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/test/java/com/jamjam/bookjeok/domains/book/command/service/BookApiServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/test/java/com/jamjam/bookjeok/domains/book/command/service/BookCommandAdminServiceImplTest.java
Labels: ♻️ 리팩토링

#24 [REFACTOR] member 엔티티 패키지명 오류 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/entity/Member.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/repository/MemberRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/FollowCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/MemberCommandServiceImpl.java
Labels: ♻️ 리팩토링, 🔨 수정

#25 [REFACTOR] import 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/auth/service/AuthService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/auth/service/CustomUserDetailsService.java
Labels: ♻️ 리팩토링

#28 [FEAT] 비밀번호 재설정 구현하기
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/build.gradle
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/controller/PasswordResetCommandController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/dto/request/PasswordModifyRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/dto/request/PasswordResetLinkRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/entity/PasswordResetToken.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/repository/PasswordResetTokenRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/EmailCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/EmailCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/PasswordResetCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/PasswordRestCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/exception/member/MemberErrorCode.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/exception/member/MemberExceptionHandler.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/exception/member/passwordResetException/ExpiredTokenException.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/exception/member/passwordResetException/NotExistTokenException.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/application.yml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/controller/PasswordResetCommandControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/service/EmailCommandServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/service/PasswordResetServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/resources/application-test.yml
Labels: 🤖 기능

#29 [FEATURE] 작가 별 도서 목록 조회 기능 구현
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/controller/BookQueryMemberController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/mapper/BookMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/book/BookMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/book/query/controller/BookQueryMemberControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/book/query/mapper/BookMapperTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberServiceImplTest.java
Labels: 🤖 기능

#30 [FEATURE] 결제 완료 시 결제 금액과 결제 방법을 주문 상세 내역과 함께 클라이언트에 반환하는 기능 추가
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/PaymentCancelDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/PaymentCardDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/PaymentDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/PaymentEasyPayDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/PaymentReceiptDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/response/PaymentConfirmResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/entity/Payment.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/entity/PaymentCard.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/entity/PaymentEasyPay.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/infrastructure/client/TossPaymentClientImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/repository/PaymentCardRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/repository/PaymentEasyPayRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentEntityCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentEntityCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/dto/PaymentDetailDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/mapper/PaymentDetailMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/mapper/PaymentMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/service/PaymentDetailService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/service/PaymentDetailServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/exception/payment/PaymentExceptionHandler.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/exception/payment/PaymentNotFountException.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/payment/PaymentDetailMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/payment/PaymentMapper.xml
Labels: 🤖 기능
