Repository jamjam-book/be15-jamjam-bookjeok-combine, pull requests merged in 2025-05, with the labels that each got.

#32 [FEATURE] WebConfig에 전역 CORS 설정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/config/WebConfig.java
Labels: 🤖 기능

#31 [REFACTOR] application-yml 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/resources/application.yml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/application.yml
Labels: ♻️ 리팩토링, ⚙ 설정

#33 [FIX] 장바구니에서 도서 추가, 수량 변경, 삭제할 때 정상작동되지 않는 부분 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/command/repository/BookRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/repository/CartRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/service/CartCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/mapper/CartMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/cart/CartMapper.xml
Labels: 🐞 버그

#36 [FEATURE] 멤버 전체 목록 조회 기능 수정 및 멤버 아이디로 멤버 조회하기 기능 추가
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/dto/request/MemberSearchRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/dto/response/MemberDetailResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/controller/AdminQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/mapper/AdminMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/service/AdminQueryService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/service/AdminQueryServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/member/AdminMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/controller/AdminQueryControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/mapper/AdminMapperTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/service/AdminServiceTest.java
Labels: 🔨 수정, 🤖 기능

#38 [FEATURE] 도서 관리자 페이지 구현을 위한 로직 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/config/WebConfig.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/controller/BookCommandAdminController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/service/BookApiService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/command/service/BookApiServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/query/controller/BookQueryAdminController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/BookDetailDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/query/mapper/BookMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryAdminService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryAdminServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/resources/application.yml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/resources/mappers/book/BookMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/test/java/com/jamjam/bookjeok/domains/book/command/service/BookApiServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/test/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryAdminServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/application.yml
Labels: ♻️ 리팩토링, ✔️ 테스트, 🔨 수정, 🤖 기능

#39 [FEATURE] 관심 작가 페이지 구현을 위한 코드 수정 및 추가
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/dto/response/InterestAuthorListResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/controller/InterestAuthorQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/dto/InterestAuthorDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/mapper/InterestAuthorMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/service/InterestAuthorQueryService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/service/InterestAuthorQueryServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/member/InterestAuthorMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/controller/InterestAuthorQueryControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/mapper/InterestAuthorMapperTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/service/InterestAuthorQueryServiceImplTest.java
Labels: ♻️ 리팩토링, ✔️ 테스트, 🔨 수정, 🤖 기능

#40 [FEATURE] 주문 내역 API 응답을 orderId 기준 그룹핑 구조로 리팩터링
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/controller/OrderController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/OrderDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/OrderItemDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/OrderResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/PageOrderResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/response/OrderResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/dto/response/PageOrderResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/repository/OrderRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/service/OrderCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/command/service/OrderCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/order/command/controller/OrderControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/order/command/service/OrderCommandServiceImplTest.java
Labels: 🤖 기능

#42 [FEATURE] 주문 상세 내역 조회 API 응답 구조 개선 및 관련 서비스 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/order/query/mapper/OrderMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/controller/OrderDetailQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/dto/OrderDetailBookDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/dto/response/OrderDetailResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/service/OrderDetailQueryService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/orderdetail/query/service/OrderDetailQueryServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/dto/response/PaymentConfirmResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/command/service/PaymentCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/service/PaymentDetailService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/payment/query/service/PaymentDetailServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/order/OrderMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/orderdetail/query/controller/OrderDetailQueryControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/orderdetail/query/service/OrderDetailQueryServiceImplTest.java
Labels: 🤖 기능

#43 [TEST] 관리자와 관심 작가 controller 테스트 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/controller/AdminQueryControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/controller/InterestAuthorQueryControllerTest.java
Labels: ✔️ 테스트

#44 [REFACTOR] 이메일 보내지는 경로 수정 및 테스트 코드 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/EmailCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/service/EmailCommandServiceImplTest.java
Labels: ♻️ 리팩토링, ✔️ 테스트

#45 [FIX] 팔로우 관련 기능 프론트와 연결되게 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/controller/FollowCommandController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/controller/FollowQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/dto/PostSummaryDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/member/FollowMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/controller/FollowCommandControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/controller/FollowQueryControllerTest.java
Labels: ♻️ 리팩토링, 🔨 수정

#46 [REFACTOR] 장바구니 등록, 수정, 삭제 엔드포인트를 `members/{memberId}/carts`로 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/controller/CartCommandController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/dto/request/CartRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/service/CartCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/service/CartCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/controller/CartQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/command/controller/CartCommandControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/command/service/CartCommandServiceImplTest.java
Labels: ♻️ 리팩토링

#47 [REFACTOR] 장바구니 조회, 등록, 수정, 삭제 응답 API 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/dto/response/CartResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/command/service/CartCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/dto/response/CartBookResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/cart/CartMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/command/controller/CartCommandControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/command/service/CartCommandServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/query/controller/CartQueryControllerTest.java
Labels: ♻️ 리팩토링

#49 [FEATURE] 회원의 장바구니 목록에 있는 도서 개수를 조회하는 기능 구현
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/controller/CartQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/dto/response/CartCountResponse.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/service/CartQueryService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/cart/query/service/CartQueryServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/cart/query/service/CartQueryServiceImplTest.java
Labels: 🤖 기능

#50 [FEATURE] 프론트에 맞게 관심 도서 기능 추가 및 수정
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/controller/InterestBookCommandController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/dto/request/InterestBookRequest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/repository/InterestBookRepository.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/InterestBookCommandService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/command/service/InterestBookCommandServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/controller/InterestBookQueryController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/dto/InterestBookDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/member/query/mapper/InterestBookMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/member/InterestBookMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/controller/InterestBookCommandControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/command/service/InterestBookCommandServiceImplTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/controller/InterestBookQueryControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/member/query/mapper/InterestBookMapperTest.java
Labels: ♻️ 리팩토링, 🔨 수정, 🤖 기능

#52 [REFACTOR] 도서 관리 이미지 저장 절대 경로 변경
  .idea/misc.xml
  .idea/modules.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok-bookAPI/src/main/java/com/jamjam/bookjeok/config/WebConfig.java
Labels: ♻️ 리팩토링

#53 [FEATURE] 사용자 도서 관련 페이지 API 연동을 위한 기능 구현
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/build.gradle
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/config/WebConfig.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/command/controller/BookCommandMemberController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/controller/BookQueryMemberController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/AuthorDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/AuthorOtherBookDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/AuthorOthersSearchCondition.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/BookCategoryDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/BookDetailPageDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/BookListPageDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/BookSearchCondition.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/PriceRangeDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/ReviewListDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/mapper/BookMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/book/BookMapper.xml
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/book/query/controller/BookQueryMemberControllerTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/book/query/mapper/BookMapperTest.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberServiceImplTest.java
Labels: ⚙ 설정, 🔨 수정, 🤖 기능

#55 [REFACTOR] 도서 검색을 위한 쿼리 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/book/BookMapper.xml
Labels: ♻️ 리팩토링

#56 [FEATURE] 메인 페이지 API 연동을 위한 로직 변경
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/controller/BookQueryMemberController.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/dto/PopularBookDTO.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/mapper/BookMapper.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberService.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/java/com/jamjam/bookjeok/domains/book/query/service/BookQueryMemberServiceImpl.java
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/main/resources/mappers/book/BookMapper.xml
Labels: ♻️ 리팩토링, 🤖 기능

#57 [FIX] application-test.yml에 os-image-dir 추가하여 테스트 코드 실패 문제 해결
  be15-jamjam-bookjeok-msa/be15-2nd-jamjam-bookjeok/src/test/resources/application-test.yml
Labels: ✔️ 테스트, 🐞 버그
